services:
    snowcap_admindemo.image_admin:
        class: Snowcap\AdminDemoBundle\Admin\ImageAdmin
        parent: snowcap_admin.admin_content
        arguments: [@router]
        tags:
            - { name: snowcap_admin.admin, alias: image, label: Image|Images }