snowcap_admin:
    security:
        user_class: Snowcap\AdminDemoBundle\Entity\AdminUser

security:
    encoders:
        Snowcap\AdminBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin_users:
            entity: { class: SnowcapAdminDemoBundle:AdminUser, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:    ^/admin
            anonymous: ~
            form_login:
                login_path:  snowcap_admin_login
                check_path:  snowcap_admin_login_check
            logout:
                path: snowcap_admin_logout

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
